### PR TITLE
Add `only` and `except` upload filter options to onesky.yml

### PR DESCRIPTION
**Pull request by samleb**
This might be useful to some people, for instance when you don't have to translate your backend admin interface and you just want these files to be skipped during the upload/download process.

### CODE REVIEW

**Comment by Knack** [comment]
Awesome, exactly what I needed! Can this PR be merged?

**Comment by VLMH** [comment]
:+1: Will review and merge soon

**Comment by zedtux** [comment]
@VLMH when could this be merged please ?

**Comment by bmedenwald** [comment]
+1

**Comment by samleb** [comment]
I've fixed the conflicts but the tests may not cover all edge cases.
Hope it'll be helpful though!

**Comment by Knack** [comment]
@VLMH  Can this PR be merged _now_?

**Comment by VLMH** [comment]
I am very sorry for late response as I was in another project.
I will do it within this week. Really sorry!

**Pull request merged**
