### PR TITLE
Feature/download base or all languages

### PR DESCRIPTION
**Pull request by zedtux**
This PR adds 2 new Rake tasks:

```
rake onesky:download_base
```
Download translations of files uploaded only for the base language.

```
rake onesky:download_all
```
Download translations of files uploaded for all the languages including the base language.

### CODE REVIEW

**Comment by VLMH** [comment]
This PR failed couple test case
In short, we aim to have options to download [`languages except base`, `base language`, `all languages`]
Due to my bad of no comments and improper method naming, I think there's some misunderstanding. Sorry!

I will pick the changes of the rake commands and implement it in a new PR.
It should be done in a few days. Thanks!

**Comment by zedtux** [comment]
@VLMH I'm not sure to have understand everything but I can't wait to see this feature available in the gem. :)

**Comment by zedtux** [comment]
@VLMH when do you think this will be available please ?

**Comment by VLMH** [comment]
@zedtux #17 is made and just need to test it with a new project.
If you are urge to have the feature, you can try modify `Gemfile` as follow to have a test.

```
gem 'onesky-rails', github: 'onesky/onesky-rails', ref: '7a91a788'
```

#17 will be merged in 1-2 days as I have other work to do.

**Pull request closed without merging**
