### PR TITLE
Update dependencies to support Ruby 2.5.0

### PR DESCRIPTION
**Pull request by davidwessman**
- Updates dependencies to support Ruby 2.5.0
- Changes Travis test matrix to [supported rubies](https://www.ruby-lang.org/en/downloads/)

### CODE REVIEW

**Comment by NadiaGubernator** [comment]
@VLMH Merge this one, please :) Current version doesn't work at all with ruby > 2.4 and falls with `KeyError: key not found: :cipher` due to dependency on `rest-client ~> 1.8.0`

**Comment by sveredyuk** [comment]
Any chance for this PR to be merged ?

**Comment by yashasvj** [comment]
@VLMH - Please merge this. Much needed for Ruby > 2.4.
Thanks in advance!

**Comment by opsb** [comment]
10 months to merge a PR that unblocks a large portion of ruby users? Is this gem no longer maintained?

**Comment by roy** [comment]
They actually fixed this themselves in master but I think they forgot to push a new gem

**Pull request closed without merging**
